spring:
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS}
    client-id: ${spring.application.name}

    properties:
      request.timeout.ms: 20000
      retry.backoff.ms: 500
      auto.create.topics.enable: false
      spring.json.add.type.headers: false

    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      enable-auto-commit: false
      auto-offset-reset: latest
      properties:
        max.poll.interval.ms: 600000   # 10분
        # 필요 시:
        # max.poll.records: 3000
        # fetch.min.bytes: 1048576
        # fetch.max.wait.ms: 5000

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    listener:
      ack-mode: manual_immediate