spring:
  application:
    name: commerce-batch
  profiles:
    active: local
  
  datasource:
    url: jdbc:mysql://localhost:3306/loopers
    username: application
    password: application
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
      
  sql:
    init:
      mode: never

scheduling:
  enabled: true
  test:
    enabled: false

logging:
  level:
    org.springframework.batch: DEBUG
    com.loopers: DEBUG
    org.springframework.scheduling: DEBUG
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,batch,scheduledtasks
  endpoint:
    health:
      show-details: always

---
spring:
  config:
    activate:
      on-profile: local
  
  datasource:
    url: jdbc:mysql://localhost:3306/loopers
    username: application
    password: application

scheduling:
  enabled: true
  test:
    enabled: true

---
spring:
  config:
    activate:
      on-profile: dev
  
  datasource:
    url: jdbc:mysql://localhost:3306/loopers
    username: application
    password: application

scheduling:
  enabled: true
  test:
    enabled: false

---
spring:
  config:
    activate:
      on-profile: qa
  
  datasource:
    url: jdbc:mysql://localhost:3306/loopers
    username: application
    password: application

scheduling:
  enabled: true
  test:
    enabled: false

---
spring:
  config:
    activate:
      on-profile: prd
  
  datasource:
    url: jdbc:mysql://localhost:3306/loopers
    username: application
    password: application

scheduling:
  enabled: true
  test:
    enabled: false

logging:
  level:
    org.springframework.batch: INFO
    com.loopers: INFO
    org.springframework.scheduling: INFO
    root: WARN
