# Spring 기본 스케줄링 설정
spring:
  task:
    scheduling:
      pool:
        size: 10
      thread-name-prefix: "spring-scheduler-"
      shutdown:
        await-termination: true
        await-termination-period: 30s

# 스케줄링 작업 설정
scheduling:
  tasks:
    # 결제 상태 동기화 작업
    payment-sync:
      enabled: true
      pending-check-minutes: 10  # 10분 이상 PENDING 상태일 때 알림

    # === 새로 추가할 아웃박스 설정 ===
    outbox-publishing:
      enabled: true
      batch-size: 100           # 한 번에 처리할 이벤트 수
      interval-seconds: 5       # 발행 간격 (초)

    outbox-cleanup:
      enabled: true
      cleanup-days: 7           # 며칠 전 이벤트까지 정리할지

# 환경별 설정
---
# 로컬/개발 환경
spring:
  config:
    activate:
      on-profile: local, dev

loopers:
  scheduling:
    pool-size: 5

scheduling:
  tasks:
    payment-sync:
      enabled: true   # 로컬에서는 결제 동기화 활성화 (테스트용)
    outbox-publishing:
      enabled: true
      interval-seconds: 3  # 로컬에서는 더 빠르게
    outbox-cleanup:
      enabled: false   # 로컬에서는 정리 비활성화

---
# 테스트 환경
spring:
  config:
    activate:
      on-profile: test

loopers:
  scheduling:
    pool-size: 3
    await-termination-seconds: 10

scheduling:
  tasks:
    payment-sync:
      enabled: false  # 테스트에서는 비활성화
    outbox-publishing:
      enabled: false  # 테스트에서는 비활성화
    outbox-cleanup:
      enabled: false

---
# QA 환경
spring:
  config:
    activate:
      on-profile: qa

loopers:
  scheduling:
    pool-size: 8
    await-termination-seconds: 45

scheduling:
  tasks:
    payment-sync:
      enabled: true
    outbox-publishing:
      enabled: true
    outbox-cleanup:
      enabled: true
      cleanup-days: 3  # QA는 더 자주 정리

---
# 운영 환경
spring:
  config:
    activate:
      on-profile: prd

loopers:
  scheduling:
    pool-size: 15
    await-termination-seconds: 60

scheduling:
  tasks:
    payment-sync:
      enabled: true
    outbox-publishing:
      enabled: true
      batch-size: 200     # 운영에서는 더 큰 배치
    outbox-cleanup:
      enabled: true
      cleanup-days: 30    # 운영에서는 30일 보관